version: '2'
services:
    mongodb:
        image: mongo:3.2.6
        ports:
            - "27017:27017"        

    mp_backend:
        build: ./backend/
        ports:
            - "9090:8080"
        links:
            - mongodb

    mp_frontend:
        build: ./front/
        ports:
            - "3000:3000"
        links:
            - mp_backend
